# Generated by Django 3.0.7 on 2020-07-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200702_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='choice',
            field=models.CharField(blank=True, choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=50, null=True),
        ),
    ]
