# Generated by Django 3.0.7 on 2020-07-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_bet_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='choice',
            field=models.CharField(blank=True, choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=50, null=True),
        ),
    ]
