# Generated by Django 3.0.7 on 2020-07-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200702_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='choice',
            new_name='result',
        ),
    ]
