# Generated by Django 3.0.7 on 2020-07-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200702_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
