# Generated by Django 3.0.7 on 2020-07-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_bet_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet',
            field=models.IntegerField(default=5),
        ),
    ]
