# Generated by Django 3.0.7 on 2020-07-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200702_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Result'),
        ),
    ]
