# Generated by Django 3.0.7 on 2020-07-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200702_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Result'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet',
            field=models.IntegerField(default=5),
        ),
    ]
