# Generated by Django 3.0.7 on 2020-07-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20200702_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('WIN', 'WIN'), ('LOSE', 'LOSE'), ('PENDING', 'PENDING')], default='PENDING', max_length=50),
        ),
    ]
